var nodemailer = require("nodemailer");

module.exports = function sendMail(data) {
  var transport = nodemailer.createTransport({
    host: "smtp.1and1.com",
    port: 465,
    auth: {
      user: "zss@narola.email", //example of generated by Mailtrap
      pass: "m(5J?<,<;8%.K4e" //example of generated by Mailtrap
    }
  });

  var mailOptions = {
    from: data.from,
    to: data.to,
    subject: data.subject,
    text: data.text,
    html: data.html
  };

  transport.sendMail(mailOptions, (error, info) => {
    if (error) {
      return error;
    }
    console.log("Email sent: " + info.response);
  });
};
